# LaTeX environment development image.
#
# Alessandro Tenaglia <alessandro.tenaglia@uniroma2.it>
# Roberto Masocco <roberto.masocco@uniroma2.it>
#
# April 21, 2026

FROM debian:trixie-slim

ARG USER_UID=1000
ARG USER_GID=${USER_UID}

ARG DEBIAN_FRONTEND=noninteractive

# Install system packages, configure locales
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    # --- Base utilities
    apt-utils \
    ca-certificates \
    curl \
    git \
    gnupg \
    less \
    locales \
    nano \
    openssh-client \
    openssl \
    procps \
    python3 \
    sudo \
    wget \
    # --- Zsh and syntax-highlighting helper
    python3-pygments \
    zsh \
    zsh-doc \
    # --- Build tooling (some LaTeX workflows call make/gcc)
    build-essential \
    make \
    # --- Graphics / conversion tools used from inside LaTeX
    ghostscript \
    inkscape \
    pandoc \
    # --- TeX Live 2024 (Debian trixie)
    biber \
    cm-super \
    latexmk \
    lmodern \
    tex-gyre \
    texlive \
    texlive-bibtex-extra \
    texlive-extra-utils \
    texlive-fonts-extra \
    texlive-font-utils \
    texlive-lang-english \
    texlive-lang-italian \
    texlive-latex-extra \
    texlive-latex-recommended \
    texlive-luatex \
    texlive-metapost \
    texlive-pictures \
    texlive-plain-generic \
    texlive-science \
    texlive-xetex \
    # --- latexindent Perl runtime deps
    libfile-homedir-perl \
    liblog-dispatch-perl \
    liblog-log4perl-perl \
    libunicode-linebreak-perl \
    libxml-libxml-perl \
    libyaml-tiny-perl && \
  echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
  locale-gen && \
  update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
  rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8

# Create non-root sudo user
RUN groupadd --gid ${USER_GID} latex && \
  useradd \
    -r \
    --create-home \
    --shell /usr/bin/zsh \
    --uid ${USER_UID} \
    --gid ${USER_GID} \
    latex && \
  install -d -o latex -g latex \
    /home/latex/workspace \
    /home/latex/zsh_history \
    /home/latex/.ssh

ENV HOME=/home/latex

# Switch to internal user
USER latex
ENV HOME=/home/latex
WORKDIR ${HOME}

# Install and configure Oh-My-Zsh + plugins + powerlevel10k
ENV ZSH=${HOME}/.oh-my-zsh
ENV ZSH_CUSTOM=${ZSH}/custom
ENV ZSH_PLUGINS=${ZSH_CUSTOM}/plugins
ENV ZSH_THEMES=${ZSH_CUSTOM}/themes

RUN sh -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended && \
  git clone --single-branch --branch 'master' --depth 1 \
    https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_PLUGINS}/zsh-syntax-highlighting && \
  git clone --single-branch --branch 'master' --depth 1 \
    https://github.com/zsh-users/zsh-autosuggestions.git     ${ZSH_PLUGINS}/zsh-autosuggestions && \
  git clone --single-branch --depth 1 \
    https://github.com/romkatv/powerlevel10k.git             ${ZSH_THEMES}/powerlevel10k

COPY --chown=latex:latex \
  ./config/.aliases.sh \
  ./config/.bashrc    \
  ./config/.nanorc    \
  ./config/.p10k.zsh  \
  ./config/.zshrc     \
  ./

CMD ["zsh"]
