# LaTeX environment images specification.
#
# Alessandro Tenaglia <alessandro.tenaglia42@gmail.com>
# Roberto Masocco <robmasocco@gmail.com>
#
# January 23, 2023

version: '3.9'

services:
  latex-env:
    build:
      context: .
      dockerfile: Dockerfile.env
      args:
        - USER_UID=1000
    image: intelligentsystemslabutv/latex-env:latest

  latex-env-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER_UID=1000
    image: intelligentsystemslabutv/latex-env:dev
    environment:
      TERM: xterm-256color
      SHELL: /usr/bin/zsh
    command: ["/bin/bash", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
