# Latex environment containers specification.
#
# Alessandro Tenaglia <alessandro.tenaglia42@gmail.com>
# Roberto Masocco <robmasocco@gmail.com>
#
# April 5, 2022

version: "3.9"

services:
  latex-env:
    build:
      context: ./
      network: host
    image: intelligentsystemslabutv/latex-env:latest
    network_mode: host
    environment:
      TERM: xterm-256color
      DISPLAY:
      SHELL: /usr/bin/zsh
    user: latex
    stdin_open: false
    tty: true
    working_dir: /home/latex/workspace
    volumes:
      - ~/.Xauthority:/home/latex/.Xauthority:rw
      - ~/.ssh:/home/latex/.ssh
      - ~/.gitconfig:/home/latex/.gitconfig
      - ../:/home/latex/workspace
